name: Run ESLint 
on: [push]
  jobs:
      eslint:
      runs-on: ubuntu-latest 
      steps:
       - name: Checkout code 
       - uses: actions/checkout@v2 
       - name: Install Node.js
         uses: actions/setup-node@v2 
         with:
          node-version:  v18.12.1 
       - name: Install dependencies 
       run: npm install 
       - name: Run ESLint 
         run: npx eslint 