name: Print Node.js version

on: [push]

jobs:
  print-node-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: v18.12.1
    - name: Print Node.js version
      run: node -v


name: Run ESLint 
on: [push] 

jobs:
  eslint:
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout code 
    - uses: actions/checkout@v2 
    - name: Install Node.js
      uses: actions/setup-node@v2 
      with:
         node-version:  v18.12.1 
    - name: Install dependencies 
      run: npm install 
    - name: Run ESLint 
      run: npx eslint 